/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HarmoniumNotesRouteImport } from './routes/harmonium-notes'
import { Route as HarmoniumSongsRouteImport } from './routes/harmonium-songs'
import { Route as HowToPlayHarmoniumRouteImport } from './routes/how-to-play-harmonium'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PlayHarmoniumOnlineRouteImport } from './routes/play-harmonium-online'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VirtualHarmoniumRouteImport } from './routes/virtual-harmonium'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmoniumNotesRoute = HarmoniumNotesRouteImport.update({
  id: '/harmonium-notes',
  path: '/harmonium-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmoniumSongsRoute = HarmoniumSongsRouteImport.update({
  id: '/harmonium-songs',
  path: '/harmonium-songs',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayHarmoniumRoute = HowToPlayHarmoniumRouteImport.update({
  id: '/how-to-play-harmonium',
  path: '/how-to-play-harmonium',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHarmoniumOnlineRoute = PlayHarmoniumOnlineRouteImport.update({
  id: '/play-harmonium-online',
  path: '/play-harmonium-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualHarmoniumRoute = VirtualHarmoniumRouteImport.update({
  id: '/virtual-harmonium',
  path: '/virtual-harmonium',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/harmonium-notes': typeof HarmoniumNotesRoute
  '/harmonium-songs': typeof HarmoniumSongsRoute
  '/how-to-play-harmonium': typeof HowToPlayHarmoniumRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/play-harmonium-online': typeof PlayHarmoniumOnlineRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-harmonium': typeof VirtualHarmoniumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/harmonium-notes': typeof HarmoniumNotesRoute
  '/harmonium-songs': typeof HarmoniumSongsRoute
  '/how-to-play-harmonium': typeof HowToPlayHarmoniumRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/play-harmonium-online': typeof PlayHarmoniumOnlineRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-harmonium': typeof VirtualHarmoniumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/harmonium-notes': typeof HarmoniumNotesRoute
  '/harmonium-songs': typeof HarmoniumSongsRoute
  '/how-to-play-harmonium': typeof HowToPlayHarmoniumRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/play-harmonium-online': typeof PlayHarmoniumOnlineRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-harmonium': typeof VirtualHarmoniumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/harmonium-notes'
    | '/harmonium-songs'
    | '/how-to-play-harmonium'
    | '/learn'
    | '/play'
    | '/play-harmonium-online'
    | '/practice'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-harmonium'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/harmonium-notes'
    | '/harmonium-songs'
    | '/how-to-play-harmonium'
    | '/learn'
    | '/play'
    | '/play-harmonium-online'
    | '/practice'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-harmonium'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/harmonium-notes'
    | '/harmonium-songs'
    | '/how-to-play-harmonium'
    | '/learn'
    | '/play'
    | '/play-harmonium-online'
    | '/practice'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-harmonium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HarmoniumNotesRoute: typeof HarmoniumNotesRoute
  HarmoniumSongsRoute: typeof HarmoniumSongsRoute
  HowToPlayHarmoniumRoute: typeof HowToPlayHarmoniumRoute
  LearnRoute: typeof LearnRoute
  PlayRoute: typeof PlayRoute
  PlayHarmoniumOnlineRoute: typeof PlayHarmoniumOnlineRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VirtualHarmoniumRoute: typeof VirtualHarmoniumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonium-notes': {
      id: '/harmonium-notes'
      path: '/harmonium-notes'
      fullPath: '/harmonium-notes'
      preLoaderRoute: typeof HarmoniumNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonium-songs': {
      id: '/harmonium-songs'
      path: '/harmonium-songs'
      fullPath: '/harmonium-songs'
      preLoaderRoute: typeof HarmoniumSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play-harmonium': {
      id: '/how-to-play-harmonium'
      path: '/how-to-play-harmonium'
      fullPath: '/how-to-play-harmonium'
      preLoaderRoute: typeof HowToPlayHarmoniumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-harmonium-online': {
      id: '/play-harmonium-online'
      path: '/play-harmonium-online'
      fullPath: '/play-harmonium-online'
      preLoaderRoute: typeof PlayHarmoniumOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-harmonium': {
      id: '/virtual-harmonium'
      path: '/virtual-harmonium'
      fullPath: '/virtual-harmonium'
      preLoaderRoute: typeof VirtualHarmoniumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HarmoniumNotesRoute: HarmoniumNotesRoute,
  HarmoniumSongsRoute: HarmoniumSongsRoute,
  HowToPlayHarmoniumRoute: HowToPlayHarmoniumRoute,
  LearnRoute: LearnRoute,
  PlayRoute: PlayRoute,
  PlayHarmoniumOnlineRoute: PlayHarmoniumOnlineRoute,
  PracticeRoute: PracticeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VirtualHarmoniumRoute: VirtualHarmoniumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
